### ISSUE TITLE
Doesn't seem to work with OSS Chef Server 10.6.2

### ISSUE THREAD

**Issue by c10l** [cassianoleal/vagrant-butcher#1]
::Chef::Node.load(node) returns a Hash instead of a Chef::Node object, causing the destroy method to raise an exception:

undefined method `destroy' for #<Hash:0x007f98febd53a0>
