### ISSUE TITLE
Does not work on Vagrant 1.5

### ISSUE THREAD

**Issue by c10l** [cassianoleal/vagrant-butcher#44]
```
Bringing machine 'dvm' up with 'virtualbox' provider...
/Users/cassiano/.vagrant.d/gems/gems/vagrant-butcher-2.1.4/lib/vagrant-butcher/env.rb:8:in `initialize': undefined method `scope' for #<Vagrant::UI::Colored:0x00000101994dd0> (NoMethodError)
    from /Users/cassiano/.vagrant.d/gems/gems/vagrant-butcher-2.1.4/lib/vagrant-butcher/action.rb:23:in `new'
    from /Users/cassiano/.vagrant.d/gems/gems/vagrant-butcher-2.1.4/lib/vagrant-butcher/action.rb:23:in `block in setup'
    from /Users/cassiano/.vagrant.d/gems/gems/vagrant-butcher-2.1.4/lib/vagrant-butcher/action.rb:22:in `tap'
    from /Users/cassiano/.vagrant.d/gems/gems/vagrant-butcher-2.1.4/lib/vagrant-butcher/action.rb:22:in `setup'
    from /Users/cassiano/.vagrant.d/gems/gems/vagrant-butcher-2.1.4/lib/vagrant-butcher/action.rb:16:in `block in copy_guest_key'
    from /Users/cassiano/.vagrant.d/gems/gems/vagrant-butcher-2.1.4/lib/vagrant-butcher/action.rb:15:in `tap'
    from /Users/cassiano/.vagrant.d/gems/gems/vagrant-butcher-2.1.4/lib/vagrant-butcher/action.rb:15:in `copy_guest_key'
    from /Users/cassiano/.vagrant.d/gems/gems/vagrant-butcher-2.1.4/lib/vagrant-butcher/plugin.rb:12:in `provision'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/action/runner.rb:45:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/action/runner.rb:45:in `block (2 levels) in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/action/runner.rb:44:in `tap'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/action/runner.rb:44:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/action/runner.rb:43:in `map'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/action/runner.rb:43:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/machine.rb:157:in `action'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/batch_action.rb:72:in `block (2 levels) in run'
```
